version: '3.8'
services:
  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
      - 9229:9229

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend-service
      target: production
    volumes:
      - /home/game-textures:/usr/src/backend/public
    command: npm run start
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: server
      JWT_TOKEN: LAUNCHER
    restart: always
    ports:
      - 4000:4000

  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    volumes:
      - /home/kladnitsky/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: server
    restart: always

  pg_admin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    ports:
      - 5440:80
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: core2pixel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    user: root
    volumes:
      - /home/kladnitsky/pgadmin-data:/var/lib/pgadmin
