name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Stop
        run: docker-compose -f docker-compose.production.yml down
      - name: Clean
        run: docker system prune -af
      - name: Pull
        run: docker-compose pull
      - name: Build
        run: docker-compose -f docker-compose.production.yml build
      - name: Up
        run: docker-compose -f docker-compose.production.yml up -d
      - name: Status
        run: docker ps -a
