name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose -f docker-compose.production.yml --env-file /home/kladnitsky/game-launcher/.env up -d
      - name: Stop
        run: docker-compose -f docker-compose.production.yml down
      - name: Build
        run: docker-compose -f docker-compose.production.yml --env-file /home/kladnitsky/game-launcher/.env build
      - name: Up
        run: docker-compose -f docker-compose.production.yml up -d
        - name: Status
        run: docker ps -a
