name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /home/kladnitsky/game-launcher

    steps:
      - uses: actions/checkout@v1
      - name: Docker Compose Test
        run: docker-compose -f docker-compose.yml up -d
      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.yml down
      - name: Build Docker Container
        run: docker-compose -f docker-compose.yml up --build
