# name: Test Workflow

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/game-launcher

    steps:
      - uses: actions/checkout@v2
      - name: Touch
        run: touch test.txt
